In [ ]:
## Vloco de codigo para instalar versao especifica dos pacotes
##pip install pandas==1.5.3
##pip install numpy==1.24.3

##### Carregando pacotes

In [36]:
# Pacotes de manipulacao

import pandas as pd
import numpy as np
import os

print("pandas:", pd.__version__)
print("numpy:", np.__version__)

pandas: 1.5.3
numpy: 1.24.3

## Carregando databases

#### Base Dados Cadastrais

In [13]:
## Carregando todos arquivos em parquet de uma pasta

path = 'database/raw/base_dados_cadastrais'

all_files = [os.path.join(path, f) for f in os.listdir(path) if f.endswith('.parquet')]
df_list = [pd.read_parquet(f, engine='pyarrow') for f in all_files]

df_base_dados_cadastrais = pd.concat(df_list, ignore_index=True)

In [14]:
df_base_dados_cadastrais.head()

,NUM_CPF,SAFRA,FLAG_INSTALACAO,FPD,PROD,flag_mig2,STATUSRF,DATADENASCIMENTO,var_03,var_02,...,var_17,var_18,var_19,var_20,var_21,var_22,var_23,var_24,var_25,CEP_3_digitos
0,77789989YZZ,202503,1,0,CMV,PRE,REGULAR,09/09/1984,33,None,...,None,None,AUX_EMRG,None,FUNC_PRIVADO,None,None,ADMITIDO,AUX_EMRG FUNC_PRIVADO,768
1,7778TYWXT9X,202412,1,0,CMV,Aquisição,REGULAR,16/08/1979,None,None,...,None,None,None,None,FUNC_PRIVADO,EMPR/DIRETOR,None,ADMITIDO,FUNC_PRIVADO EMPR/DIRETOR,490
2,7778XUZNYU9,202410,1,0,CMV,PRE,REGULAR,23/07/1981,4,None,...,None,None,None,None,FUNC_PRIVADO,None,None,DISPENSADO,FUNC_PRIVADO,689
3,7778YY8WZZZ,202411,0,None,CMV,None,REGULAR,10/01/1976,48,None,...,None,None,AUX_EMRG,None,FUNC_PRIVADO,None,None,ADMITIDO,AUX_EMRG FUNC_PRIVADO,934
4,7779TX8ZTXT,202410,1,1,CMV,Aquisição,REGULAR,24/02/1982,4,None,...,None,None,None,None,FUNC_PRIVADO,EMPR/DIRETOR,None,DISPENSADO,FUNC_PRIVADO EMPR/DIRETOR,455

In [15]:
df_base_dados_cadastrais.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900378 entries, 0 to 3900377
Data columns (total 33 columns):
 #   Column            Dtype
---  ------            -----
 0   NUM_CPF           object
 1   SAFRA             object
 2   FLAG_INSTALACAO   object
 3   FPD               object
 4   PROD              object
 5   flag_mig2         object
 6   STATUSRF          object
 7   DATADENASCIMENTO  object
 8   var_03            object
 9   var_02            object
 10  var_04            object
 11  var_05            object
 12  var_06            object
 13  var_07            object
 14  var_08            object
 15  var_09            object
 16  var_10            object
 17  var_11            object
 18  var_12            object
 19  var_13            object
 20  var_14            object
 21  var_15            object
 22  var_16            object
 23  var_17            object
 24  var_18            object
 25  var_19            object
 26  var_20            object
 27  var_21            object
 28  var_22            object
 29  var_23            object
 30  var_24            object
 31  var_25            object
 32  CEP_3_digitos     object
dtypes: object(33)
memory usage: 982.0+ MB

#### Base Score Bureau Movel

In [16]:
## Carregando todos arquivos em parquet de uma pasta

path = 'database/raw/base_score_bureau_movel/base_score_bureau_movel'

all_files = [os.path.join(path, f) for f in os.listdir(path) if f.endswith('.parquet')]
df_list = [pd.read_parquet(f, engine='pyarrow') for f in all_files]

df_base_score_bureau_movel = pd.concat(df_list, ignore_index=True)

In [17]:
df_base_score_bureau_movel.head()

    SAFRA FLAG_INSTALACAO FPD PROD flag_mig2 SCORE_01 SCORE_02      NUM_CPF
0  202410               1   0  CMV       PRE      562      636  ZZZZZX7XWY8
1  202410               1   1  CMV       PRE      546      518  ZZZZZX88YXY
2  202410               1   0  CMV       PRE      621      750  ZZZZZYT7XYT
3  202410               1   1  CMV       PRE      609      679  ZZZZZNTXY9Z
4  202410               1   0  CMV       PRE      621      722  ZZZZZ79ZXUX

In [18]:
df_base_score_bureau_movel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1290526 entries, 0 to 1290525
Data columns (total 8 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   SAFRA            1290526 non-null  object
 1   FLAG_INSTALACAO  1290526 non-null  object
 2   FPD              1290526 non-null  object
 3   PROD             1290526 non-null  object
 4   flag_mig2        1290526 non-null  object
 5   SCORE_01         1281087 non-null  object
 6   SCORE_02         1289950 non-null  object
 7   NUM_CPF          1290526 non-null  object
dtypes: object(8)
memory usage: 78.8+ MB

#### Base Telco

In [19]:
## Carregando todos arquivos em parquet de uma pasta

path = 'database/raw/base_telco/base_telco'

all_files = [os.path.join(path, f) for f in os.listdir(path) if f.endswith('.parquet')]
df_list = [pd.read_parquet(f, engine='pyarrow') for f in all_files]

df_base_telco = pd.concat(df_list, ignore_index=True)

In [20]:
df_base_telco.head()

,NUM_CPF,SAFRA,FLAG_INSTALACAO,FPD,PROD,flag_mig2,var_26,var_27,var_28,var_29,...,var_84,var_85,var_86,var_87,var_88,var_89,var_90,var_91,var_92,var_93
0,7779ZY78YXT,202411,1,1,CMV,PRE,1,1,0,80.93,...,304,304,1,3,6,0,1.33,1,2,0
1,777YXTNZWZN,202410,1,0,CMV,PRE,1,1,0,304,...,304,304,3,3,1,0,0.99,5,1,0
2,777ZXUXZZXT,202503,1,0,CMV,PRE,1,1,84.86,99.99,...,304,304,3,1,1,17,1.24,5,1,1
3,777ZXZTUU7Y,202412,1,0,CMV,PRE,1,1,25.5,87.98,...,304,304,304,304,304,304,304,304,304,304
4,7788N7YZN87,202412,1,0,CMV,PRE,1,1,0,70.39,...,1,1,0,1,1,100,1.02,1,1,6

In [21]:
df_base_telco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1367104 entries, 0 to 1367103
Data columns (total 74 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   NUM_CPF          1367104 non-null  object
 1   SAFRA            1367104 non-null  object
 2   FLAG_INSTALACAO  1367104 non-null  object
 3   FPD              1321168 non-null  object
 4   PROD             1367104 non-null  object
 5   flag_mig2        1308974 non-null  object
 6   var_26           1365809 non-null  object
 7   var_27           1365809 non-null  object
 8   var_28           1365809 non-null  object
 9   var_29           1365809 non-null  object
 10  var_30           1365809 non-null  object
 11  var_31           1365809 non-null  object
 12  var_32           1365809 non-null  object
 13  var_33           1365809 non-null  object
 14  var_34           1365809 non-null  object
 15  var_35           1365809 non-null  object
 16  var_36           1365809 non-null  object
 17  var_37           1365809 non-null  object
 18  var_38           1365809 non-null  object
 19  var_39           1365809 non-null  object
 20  var_40           1365809 non-null  object
 21  var_41           1365809 non-null  object
 22  var_42           1365809 non-null  object
 23  var_43           1365809 non-null  object
 24  var_44           1365809 non-null  object
 25  var_45           1365809 non-null  object
 26  var_46           1365809 non-null  object
 27  var_47           1365809 non-null  object
 28  var_48           1365809 non-null  object
 29  var_49           1365809 non-null  object
 30  var_50           1365809 non-null  object
 31  var_51           1365809 non-null  object
 32  var_52           1365809 non-null  object
 33  var_53           1365809 non-null  object
 34  var_54           1365809 non-null  object
 35  var_55           1365809 non-null  object
 36  var_56           1365809 non-null  object
 37  var_57           1365809 non-null  object
 38  var_58           1365809 non-null  object
 39  var_59           1365809 non-null  object
 40  var_60           1365809 non-null  object
 41  var_61           1365809 non-null  object
 42  var_62           1365809 non-null  object
 43  var_63           1365809 non-null  object
 44  var_64           1365809 non-null  object
 45  var_65           1365809 non-null  object
 46  var_66           1365809 non-null  object
 47  var_67           1365809 non-null  object
 48  var_68           1365809 non-null  object
 49  var_69           1365809 non-null  object
 50  var_70           1365809 non-null  object
 51  var_71           1365809 non-null  object
 52  var_72           1365809 non-null  object
 53  var_73           1365809 non-null  object
 54  var_74           1365809 non-null  object
 55  var_75           1365809 non-null  object
 56  var_76           1365809 non-null  object
 57  var_77           1365809 non-null  object
 58  var_78           1367104 non-null  object
 59  var_79           1367104 non-null  object
 60  var_80           1367104 non-null  object
 61  var_81           1367104 non-null  object
 62  var_82           1367104 non-null  object
 63  var_83           1367104 non-null  object
 64  var_84           1367104 non-null  object
 65  var_85           1367104 non-null  object
 66  var_86           1367104 non-null  object
 67  var_87           1367104 non-null  object
 68  var_88           1367104 non-null  object
 69  var_89           1367104 non-null  object
 70  var_90           1367104 non-null  object
 71  var_91           1367104 non-null  object
 72  var_92           1367104 non-null  object
 73  var_93           1367104 non-null  object
dtypes: object(74)
memory usage: 771.8+ MB

#### Book de Pagamento

In [23]:
## Carregando todos arquivos em parquet de uma pasta

path = 'database/raw/book_pagamento/book_pagamento/dados_pagamento'

all_files = [os.path.join(path, f) for f in os.listdir(path) if f.endswith('.parquet')]
df_list = [pd.read_parquet(f, engine='pyarrow') for f in all_files]

df_base_pagamento = pd.concat(df_list, ignore_index=True)

In [24]:
df_base_pagamento.head()

,NUM_CPF,DAT_STATUS_FATURA,CONTRATO,SEQ_FATURA,NUM_SUB_SEQ_FATURA,NUM_CREDITO_SEQ,DW_TIPO_FATURA,IND_STATUS_FATURA,DW_NUM_CLIENTE,DW_AREA,...,VAL_PAGAMENTO_CREDITO,IND_TIPO_CREDITO,SEQ_PAGAMENTO_CREDITO,SEQ_FATURA_CREDITO,COD_ALOCACAO_CREDITO,COD_DESALOCACAO_CREDITO,SEQ_ENTIDADE_CREDITO,COD_TIPO_FATURA,DAT_ATIVIDADE_CREDITO,DAT_VENCIMENTO_CREDITO
0,7NYTZUUZX78,14MAR2025:00:00:00,909421358,5,5,5,-2,C,1470063627,-3,...,39.89,P,5,5,PYM,None,5,B,14MAR2025:00:00:00,20MAR2025:00:00:00
1,Z98XTT9XUZX,07OCT2023:00:00:00,887727762,15,24,17,-2,C,1400318892,-3,...,None,None,None,None,None,None,None,None,None,None
2,8W7XU87XN9X,30MAY2024:00:00:00,896411261,13,13,13,-2,C,1399351973,-3,...,30.59,P,13,13,PYM,None,14,B,30MAY2024:00:00:00,10JUN2024:00:00:00
3,ZXY9X7ZYXNU,09JUL2024:00:00:00,889406152,23,23,25,-2,C,1206089505,-3,...,64.91,P,25,23,PYM,None,40,B,09JUL2024:00:00:00,15JUL2024:00:00:00
4,NWTWUY9ZXZZ,22FEB2024:00:00:00,888566226,20,20,19,-2,C,1201156657,-3,...,None,None,None,None,None,None,None,None,None,None

In [25]:
df_base_pagamento.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21829628 entries, 0 to 21829627
Data columns (total 73 columns):
 #   Column                        Dtype
---  ------                        -----
 0   NUM_CPF                       object
 1   DAT_STATUS_FATURA             object
 2   CONTRATO                      object
 3   SEQ_FATURA                    object
 4   NUM_SUB_SEQ_FATURA            object
 5   NUM_CREDITO_SEQ               object
 6   DW_TIPO_FATURA                object
 7   IND_STATUS_FATURA             object
 8   DW_NUM_CLIENTE                object
 9   DW_AREA                       object
 10  DW_UN_NEGOCIO                 object
 11  DW_FORMA_PAGAMENTO            object
 12  VAL_PAGAMENTO_FATURA          object
 13  DAT_CRIACAO_DW                object
 14  DW_BANCO                      object
 15  DW_TIPO_PAGAMENTO             object
 16  NUM_BANCO_PAGAMENTO           object
 17  NUM_AGENCIA_PAGAMENTO         object
 18  NUM_CC_PAGAMENTO              object
 19  DW_MOTIVO_ESTORNO             object
 20  VAL_DESCONTO_ITEM             object
 21  VAL_PAGAMENTO_ITEM            object
 22  VAL_JUROS_MULTAS_ITEM         object
 23  VAL_MULTA_EQUIP_ITEM          object
 24  VAL_MULTA_EQUIP_TOTAL         object
 25  VAL_MULTA_FID_ITEM            object
 26  COD_ORIGEM_NETUNO             object
 27  COD_CONTA_ATIVIDADE           object
 28  SEQ_ENTIDADE_ATIVIDADE        object
 29  DAT_CRIACAO_ATIVIDADE         object
 30  DAT_ATUALIZACAO_ATIVIDADE     object
 31  COD_LOGIN_OPERADOR_ATIVIDADE  object
 32  COD_ATIVIDADE                 object
 33  COD_RAZAO_ATIVIDADE           object
 34  DAT_BAIXA_ATIVIDADE           object
 35  VAL_BAIXA_ATIVIDADE           object
 36  DAT_DEPOSITO_ATIVIDADE        object
 37  COD_FUNDO_ATIVIDADE           object
 38  COD_BANCO_ATIVIDADE           object
 39  NUM_CONTA_ATIVIDADE           object
 40  COD_AGENCIA_ATIVIDADE         object
 41  SEQ_ENTIDADE_PAGAMENTO        object
 42  DAT_CRIACAO_PAGAMENTO         object
 43  DAT_ATUALIZACAO_PAGAMENTO     object
 44  COD_LOGIN_PAGAMENTO           object
 45  COD_FORMA_PAGAMENTO           object
 46  VAL_ORIGINAL_PAGAMENTO        object
 47  NUM_FATURA_PAGAMENTO          object
 48  COD_TIPO_PAGAMENTO            object
 49  DSC_NOME_BANCO_PAGAMENTO      object
 50  SEQ_ARQUIVO_PAGAMENTO         object
 51  NUM_PARCELA_PAGAMENTO         object
 52  NUM_AGRUPADOR_PAGAMENTO       object
 53  DSC_PAGAMENTO                 object
 54  VAL_ATUAL_PAGAMENTO           object
 55  COD_METODO_PAGAMENTO          object
 56  IND_STATUS_PAGAMENTO          object
 57  DAT_STATUS_PAGAMENTO          object
 58  COD_ARQUIVO_PAGAMENTO         object
 59  COD_NETUNO_PAGAMENTO          object
 60  DAT_CRIACAO_CREDITO           object
 61  DAT_ATUALIZACAO_CREDITO       object
 62  COD_LOGIN_CREDITO             object
 63  VAL_PAGAMENTO_CREDITO         object
 64  IND_TIPO_CREDITO              object
 65  SEQ_PAGAMENTO_CREDITO         object
 66  SEQ_FATURA_CREDITO            object
 67  COD_ALOCACAO_CREDITO          object
 68  COD_DESALOCACAO_CREDITO       object
 69  SEQ_ENTIDADE_CREDITO          object
 70  COD_TIPO_FATURA               object
 71  DAT_ATIVIDADE_CREDITO         object
 72  DAT_VENCIMENTO_CREDITO        object
dtypes: object(73)
memory usage: 11.9+ GB

#### Base Recarga

In [26]:
## Carregando todos arquivos em parquet de uma pasta

path = 'database/raw/bases_recarga/bases_recarga/BI_FP_ASS_RECARGA_CMV_NOVA'

all_files = [os.path.join(path, f) for f in os.listdir(path) if f.endswith('.parquet')]
df_list = [pd.read_parquet(f, engine='pyarrow') for f in all_files]

df_base_recarga = pd.concat(df_list, ignore_index=True)

In [27]:
df_base_recarga.head()

,NUM_CPF,DW_NUM_NTC,DAT_INSERCAO_CREDITO,HOR_INSERCAO_CREDITO,DW_NUM_CLIENTE,COD_TECNOLOGIA_DW,COD_CANAL_AQUISICAO,COD_TIPO_CREDITO,COD_PROMOCAO,VAL_CREDITO_INSERIDO,...,IND_METODO_PAGAMENTO,DW_PLANO_TARIFACAO,DW_TIPO_RECARGA,DW_TIPO_INSERCAO,DW_FORMA_PAGAMENTO,DW_INSTITUICAO,COD_GRUPO_CARTAO,DSC_GRUPO_CARTAO_WPP,FLAG_SOS,VALOR_SOS
0,89UU788W7TW,712481754,09OCT2023:00:00:00,170410,1369129520,GSM,17598,PE,-1,20.00,...,A,606234,-2,-2,-2,-2,UB,Rec.Online,0,None
1,Z9Y7Y9ZNN9T,799107776,25MAR2025:00:00:00,65703,1491240998,GSM,-2,PE,-1,0.00,...,A,369889,-2,-2,-2,-2,FT,NaoSeAplica,0,None
2,W7T8UNX9878,739450945,12MAR2025:00:00:00,32753,1486001611,GSM,-3,PE,-1,0.00,...,A,668900,-2,-2,-2,-1,WT,NaoSeAplica,0,None
3,X87NNXNT8ZN,763847287,12FEB2024:00:00:00,124755,1437663095,GSM,-3,PE,-1,0.00,...,A,541200,-2,-2,-2,-1,PY,NaoSeAplica,0,None
4,ZXZ7UTU9U7W,778845955,17DEC2024:00:00:00,151109,1460735683,GSM,15987,PE,-1,25.00,...,A,668901,-2,-2,-2,14434,UC,Rec.Online,0,None

In [28]:
df_base_recarga.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100213651 entries, 0 to 100213650
Data columns (total 24 columns):
 #   Column                 Dtype
---  ------                 -----
 0   NUM_CPF                object
 1   DW_NUM_NTC             object
 2   DAT_INSERCAO_CREDITO   object
 3   HOR_INSERCAO_CREDITO   object
 4   DW_NUM_CLIENTE         object
 5   COD_TECNOLOGIA_DW      object
 6   COD_CANAL_AQUISICAO    object
 7   COD_TIPO_CREDITO       object
 8   COD_PROMOCAO           object
 9   VAL_CREDITO_INSERIDO   object
 10  VAL_BONUS              object
 11  VAL_REAL               object
 12  COD_PLATAFORMA_ATU     object
 13  COD_STATUS_PLATAFORMA  object
 14  IND_METODO_PAGAMENTO   object
 15  DW_PLANO_TARIFACAO     object
 16  DW_TIPO_RECARGA        object
 17  DW_TIPO_INSERCAO       object
 18  DW_FORMA_PAGAMENTO     object
 19  DW_INSTITUICAO         object
 20  COD_GRUPO_CARTAO       object
 21  DSC_GRUPO_CARTAO_WPP   object
 22  FLAG_SOS               object
 23  VALOR_SOS              object
dtypes: object(24)
memory usage: 17.9+ GB

#### Book Atraso

In [30]:
## Carregando todos arquivos em parquet de uma pasta

path = 'database/raw/book_atraso/book_atraso/dados_faturamento/'

all_files = [os.path.join(path, f) for f in os.listdir(path) if f.endswith('.parquet')]
df_list = [pd.read_parquet(f, engine='pyarrow') for f in all_files]

df_base_atraso = pd.concat(df_list, ignore_index=True)

In [31]:
df_base_atraso.head()

,NUM_CPF,DAT_REFERENCIA,NUM_FATURA_HASH,NUM_ENT_SEQ_FATURA,CONTRATO,DW_UN_NEGOCIO,DW_HIS_PONTO_VENDA_COMTA,DW_NUM_CLIENTE,DW_AREA,DW_CICLO,...,VAL_FAT_BRUTO_BC,VAL_FAT_PAGAMENTO_BRUTO,VAL_FAT_ABERTO,VAL_FAT_ABERTO_LIQ,VAL_MULTA_JUROS,VAL_MULTA_CANCELAMENTO,VAL_PARC_APARELHO_LIQ,VAL_FAT_LIQ_JM_MC,DAT_ATIVACAO_CONTA_CLI,DAT_CRIACAO_DW
0,ZWYYNTNXTZY,01MAR2025:00:00:00,04ec0afcca62784f74854072247c5f6974b8eefb6d2ab2...,15,898134182,8,4206599,1408598449,46,99,...,1.96,0.00,1.96,0.00,1.96,0.00,0.00,0.00,04JUL2023:00:00:00,04MAR2025:01:19:01
1,Y9U9T7TN8U7,01JAN2025:00:00:00,ee4fbd4c534a8fccabee9a61ed8125bcf52502d400da44...,126,866260474,4,6325938,1074619995,18,75,...,107.63,0.00,107.63,104.74,2.89,0.00,0.00,104.74,23JAN2020:00:00:00,04JAN2025:12:38:45
2,ZNYWZ88Y7UU,01MAR2025:00:00:00,b44d880e88e41f70322ef401006b871077d2e746e249cf...,27,887369721,1,9863292,1194846811,1,16,...,37.09,0.00,37.09,36.28,0.81,0.00,0.00,36.28,06MAY2022:00:00:00,04MAR2025:00:56:12
3,79X9TWTZ8TW,01JUN2024:00:00:00,8b8bc6e04d989928b9084f98e86af1feb39cfb95b18c1e...,167,847396389,4,3673168,1050525697,17,26,...,5.44,0.00,5.44,5.31,0.13,0.00,0.00,5.31,27NOV2017:00:00:00,04JUN2024:05:50:59
4,YX9UUT99878,01NOV2024:00:00:00,6f37a401d564bd9b76087f443e6c90169940b61d0d7260...,54,894562192,4,7987677,1389109518,19,73,...,171.98,0.00,171.98,167.30,4.68,0.00,0.00,167.30,04FEB2023:00:00:00,04NOV2024:15:30:07

In [32]:
df_base_atraso.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31611316 entries, 0 to 31611315
Data columns (total 50 columns):
 #   Column                        Dtype
---  ------                        -----
 0   NUM_CPF                       object
 1   DAT_REFERENCIA                object
 2   NUM_FATURA_HASH               object
 3   NUM_ENT_SEQ_FATURA            object
 4   CONTRATO                      object
 5   DW_UN_NEGOCIO                 object
 6   DW_HIS_PONTO_VENDA_COMTA      object
 7   DW_NUM_CLIENTE                object
 8   DW_AREA                       object
 9   DW_CICLO                      object
 10  DW_TIPO_CLIENTE_CONTA         object
 11  DW_OFERTA                     object
 12  DW_FAIXA_AGING_FATURA         object
 13  DW_FAIXA_AGING_DIVIDA         object
 14  DW_FAIXA_TEMPO_BASE           object
 15  DW_FAIXA_AGING_PROX_FECH      object
 16  DW_TIPO_FATURAMENTO           object
 17  COD_PLATAFORMA                object
 18  DAT_CRIACAO_REGISTRO_TRANS    object
 19  DAT_ALTERACAO_REGISTRO_TRANS  object
 20  DAT_CANCELAMENTO_FAT          object
 21  DAT_ORIGINAL_VCTO_FAT         object
 22  DAT_ALTERACAO_VCTO_FAT        object
 23  DAT_CRIACAO_FAT               object
 24  DAT_VENCIMENTO_FAT            object
 25  DAT_STATUS_FAT                object
 26  DAT_MIN_VENCIMENTO_FAT        object
 27  NUM_BILL_SEQ_FAT              object
 28  NUM_SEQ_ACORDO_FAT            object
 29  IND_ISENCAO_COB_FAT           object
 30  IND_WO                        object
 31  IND_PDD                       object
 32  IND_PCCR                      object
 33  IND_ACA                       object
 34  IND_PRIMEIRA_FAT              object
 35  IND_FRAUDE                    object
 36  VAL_FAT_LIQUIDO               object
 37  VAL_FAT_BRUTO                 object
 38  VAL_FAT_CREDITO               object
 39  VAL_FAT_AJUSTE                object
 40  VAL_FAT_BRUTO_BC              object
 41  VAL_FAT_PAGAMENTO_BRUTO       object
 42  VAL_FAT_ABERTO                object
 43  VAL_FAT_ABERTO_LIQ            object
 44  VAL_MULTA_JUROS               object
 45  VAL_MULTA_CANCELAMENTO        object
 46  VAL_PARC_APARELHO_LIQ         object
 47  VAL_FAT_LIQ_JM_MC             object
 48  DAT_ATIVACAO_CONTA_CLI        object
 49  DAT_CRIACAO_DW                object
dtypes: object(50)
memory usage: 11.8+ GB